---
title: "Chapter 3 - Formatting Data for Covariate Download and Extraction"
author: "Rory Macklin"
date: "2026-03-25"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Chapter 3 - Formatting Data for Covariate Download and Extraction}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Chapter 3: Formatting Data for Covariate Download and Extraction

##### Author: Rory Macklin

> Satellite Earth Observation (SEO) data are an increasingly critical tool in ecological analysis, but can be difficult for end-users to access. With the functions we describe in this chapter, we aim to make several commonly used data types easy to download and attach to bird data downloaded from NatureCounts. The first step in this process is often formatting your bird data to prepare it for use in extracting data from covariate data sets.

This tutorial assumes you have a basic understanding of working with spatial data in R. For a good introduction to these kinds of operations, the [NatureCounts Spatial Data Tutorial](https://github.com/BirdsCanada/NatureCounts_SpatialData_Tutorial) can serve as a useful starting point. It explains how to download, process, and visualize spatial data, including NatureCounts surveys, conservation areas, and environmental layers.

# 3.0 Learning Objectives

By the end of **Chapter 3 - Formatting Data for Covariate Download and Extraction**, users will know how to:

-   Use `data_fmt()` to conform their data (whether it is from NatureCounts or not) to a standard format for covariate extraction: [Formatting with `data_fmt()`](#3.1formatting).
-   Use `data_buff()` to create spatial buffers around their survey points to summarize environmental variables at larger scales: [Buffering with `data_buff()`](#3.2buffering).

This R tutorial requires the following packages:

``` r
library(naturecounts)
library(tidyverse)
```

# 3.1 Formatting with `data_fmt()`{#3.1formatting}

Extracting environmental data usually requires a few data features, all of which are commonly collected during ecological surveys. These usually include:

-   The location where observations were made (usually a latitude/longitude coordinate).
-   The date on which observations were made.

# 3.2 Buffering with `data_buff()`{#3.2buffering}
