---
title: "Chapter 2 - Downloading and Extracting Landcover Data"
author: "Rory Macklin"
date: "2026-04-01"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Chapter 2 - Downloading and Extracting Landcover Data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

# Chapter 2: Downloading and Extracting Landcover Data

##### Author: Rory Macklin

> Animal communities are strongly responsive to the landcover composition of an area, as this often determines important factors such as prey availability, available habitat for foraging and breeding, and the presence of certain disturbance types. Landcover data is, however, difficult to summarize from on-the-ground observation, especially at larger spatial scales. Luckily, SEO products are available that summarize land cover composition across the globe.

This tutorial assumes you have a basic understanding of working with spatial data in R. For a good introduction to these kinds of operations, the [NatureCounts Spatial Data Tutorial](https://github.com/BirdsCanada/NatureCounts_SpatialData_Tutorial) can serve as a useful starting point. It explains how to download, process, and visualize spatial data, including NatureCounts surveys, conservation areas, and environmental layers. This tutorial also uses functions demonstrated in [**Chapter 1: Formatting Data for Covariate Download and Extraction**](4.1-CovariateFormatting.html). If you are unfamiliar with these functions, we recommend using the previous tutorial to learn to conform your data to a standardized format used in landcover download and extraction functions.

# 2.0 Learning Objectives

By the end of **Chapter 2 - Downloading and Extracting Landcover Data**, users will know how to:

- Have a basic understanding of the MODIS Terra/Aqua Landcover product accessed through `landcover_download()` and `landcover_extract()`: [MODIS Terra/Aqua Landcover Data](#2.1modis)
- Use `landcover_download()` to download MODIS Landcover data ready to match to observations in your data: [Downloading landcover data with `landcover_download()`](#2.2download).
- Use `landcover_extract()` to extract and summarize landcover data for each observation in their data: [Extracting landcover data with `landcover_extract()`](#2.3extract).

This R tutorial requires the following packages:

``` r
library(naturecounts)
library(tidyverse)
library(sf)
library(terra)
```

# 2.1 MODIS Terra/Aqua Landcover Data {#2.1modis}

The [MODIS MCD12Q1 Landcover product](https://ladsweb.modaps.eosdis.nasa.gov/missions-and-measurements/products/MCD12Q1) is a long-running, global dataset of gridded landcover type data. Each grid cell is approximately 500 m x 500 m and the data has an annual resolution. This massive spatial and temporal coverage makes this dataset one of the primary resources for landcover data, being widely incorporated into ecological analyses, including important products such as [eBird Status and Trends estimates](https://science.ebird.org/en/status-and-trends).

The raw spectral data from the MODIS Terra and Aqua satellites are processed to assign each grid cell to a landcover category. There are five available landcover classification schema:

- International Geosphere-Biosphere Program (IGBP) scheme: a 17-class scheme with 11 natural vegetation classes, three human-altered classes, and three non-vegetated classes.
- University of Maryland (UMD) scheme: a 16-class scheme with 11 natural vegetation classes, three human-altered classes, and two non-vegetated classes. Differs from IGBP by combining barren and permanent snow and ice classes into one non-vegetated lands class.
- Leaf Area Index (LAI) scheme: a 11-class scheme with eight vegetated classes (which describe natural vegetation as well as cropland), one human-altered class (focusing only on impervious surfaces), and two non-vegetated classes.
- BIOME-Biogeochemical Cycles (BGC) scheme: a 9-class scheme with six vegetation classes (which describe natural vegetation as well as cropland), one human-altered class (focusing only on impervious surfaces), and two non-vegetated classes.
- Plant Functional Type (PFT) scheme: a 12-class scheme, with six natural vegetation classes, three human-altered classes (with separation between cereal and broadleaf croplands), and three non-vegetated classes.

Users should consider which scheme and level of detail best suits their research question/study system before proceeding to using these data. This may mean considering the level of landcover detail they wish to understand a study species' response to (*"do I care whether my species responds to needleleaf or broadleaf trees differently?"*), ensuring a particular habitat type is described by their selected scheme (*"I am studying the effect of croplands on my species, so I should make sure to choose a scheme with the appropriate cropland category."*), or trying multiple schema and checking whether any categories are poorly represented in their study area (*"Hm, not much representation of barren or snow and ice landcover, maybe I'll choose a scheme that lumps those into a larger, more represented category."*)

# 2.2 Downloading landcover data with `landcover_download()` {#2.2download}

Rather than delivering one file covering the entire globe in a given year, MODIS landcover data is broken up into large tiles that cover a section of the globe, with one file for each tile per year. This means that a user would typically have to identify which tile(s) their study region falls within and manually download the appropriate files for each study year. This can be a complex and error-prone process, ultimately taking the researcher's time away from doing the research they aim to do.

Identifying this issue, R packages such as [`luna`](https://github.com/rspatial/luna/) have emerged to automate this process. In `landcover_download()`, we employ functions from `luna` and add quality of life features to further automate the downloading of MODIS landcover data.

First, lets prep some data from NatureCounts for use in downloading MODIS data using `data_fmt()`. `landcover_download()` requires input data in either `sf` or `terra` spatial format with information on observation year stored in its own column. You can provide your own data in this format, or use the built-in `naturecounts::data_fmt()` function to conform your data to the necessary format.

``` r
# This dataset containing Black-capped Chickadee observations included in
# the naturecounts R package is in a data.frame format, and contains the columns
# we need! We'll need to to convert it into an sf object for use in landcover_download().
bcch %>%
  select(latitude, longitude, survey_year) %>%
  head()
#>   latitude longitude survey_year
#> 1 45.51110 -77.50533        2011
#> 2 45.63436 -77.07484        2010
#> 3 45.82732 -77.12012        2010
#> 4 45.48730 -77.74651        2011
#> 5 45.61956 -77.23577        2010
#> 6 45.82851 -77.11430        2011
  
# We can make a call to data_fmt() to automatically convert this to an sf object
# ready to work with naturecounts' covariate download and extraction functions. We
# can ignore the warning as EPSG:4326 is an appropriate CRS for our data.
formatted <- data_fmt(bcch)
#> [Data Formatting] beginning formatting.
#> Warning: [Data Formatting] as the 'crs' argument is not specified, data CRS is assumed to be
#> EPSG:4326.

head(formatted)
#> Simple feature collection with 6 features and 6 fields
#> Geometry type: POINT
#> Dimension:     XY
#> Bounding box:  xmin: 1426543 ymin: 792053.4 xmax: 1473174 ymax: 841722.6
#> Projected CRS: Canada_Albers_Equal_Area_Conic
#>   SurveyAreaIdentifier latitude longitude survey_year survey_month survey_day
#> 1    FilledSurveyArea1 45.51110 -77.50533        2011            2         12
#> 2    FilledSurveyArea2 45.63436 -77.07484        2010            7          3
#> 3    FilledSurveyArea3 45.82732 -77.12012        2010            6         19
#> 4    FilledSurveyArea4 45.48730 -77.74651        2011            5          5
#> 5    FilledSurveyArea5 45.61956 -77.23577        2010            6         16
#> 6    FilledSurveyArea6 45.82851 -77.11430        2011           10          2
#>                   geometry
#> 1 POINT (1444206 799722.4)
#> 2 POINT (1473174 822088.3)
#> 3 POINT (1463861 841469.8)
#> 4 POINT (1426543 792053.4)
#> 5 POINT (1461424 817010.6)
#> 6 POINT (1464264 841722.6)
```

The only other prerequisite here is an [EarthData](https://urs.earthdata.nasa.gov/users/new) account, which is necessary to access MODIS data stored in the NASA EarthData Archive. Users can register at the link above.

Supplying our formatted data and EarthData account email to `landcover_download()` will begin the download process. If the user wishes to just see which files would be downloaded without executing the download, they can do so by setting `ed_transfer` to `FALSE`. Your EarthData account password can either be stored in your .Renviron file by adding the line `EarthData_password = "yourpassword"` or can be supplied through the resulting pop-up window if no `Earthdata_password` is found in your .Renviron. This is done securely using the `askpass` package used in `naturecounts` functions.

``` r
# Let's see which files would be downloaded for our data

files <- landcover_download(data = formatted,
                            ed_transfer = FALSE,
                            progress = FALSE)
#> [MODIS Landcover Download] fetching data filenames.
#> Warning: [MODIS Landcover Download] MODIS landcover data unavailable for all years before 2001.
#> landcover_extract() will extract landcover data from 2001 for these observations.

head(files)
#> [1] "MCD12Q1.A2001001.h12v04.061.2022146050354.hdf" "MCD12Q1.A2002001.h12v04.061.2022147215712.hdf"
#> [3] "MCD12Q1.A2003001.h12v04.061.2022151161906.hdf" "MCD12Q1.A2004001.h12v04.061.2022152043252.hdf"
#> [5] "MCD12Q1.A2005001.h12v04.061.2022152140219.hdf" "MCD12Q1.A2006001.h12v04.061.2022202151028.hdf"

# Now, by providing an EarthData login email, we can execute the download. Files will be downloaded into a 'modis/' subdirectory in your current working directory. 

ed_email <- "your EarthData email"

files <- landcover_download(data = formatted,
                            ed_email = ed_email,
                            progress = FALSE,
                            ed_transfer = TRUE) # We don't need to specify this as
                                                # TRUE is the default, but we have
                                                # done so for clarity.
#> [MODIS Landcover Download] downloading data.
#> Warning: [MODIS Landcover Download] MODIS landcover data unavailable for all years before 2001.
#> landcover_extract() will extract landcover data from 2001 for these observations.

head(files)
#> [1] "./modis/MCD12Q1/MCD12Q1.A2001001.h12v04.061.2022146050354.hdf"
#> [2] "./modis/MCD12Q1/MCD12Q1.A2002001.h12v04.061.2022147215712.hdf"
#> [3] "./modis/MCD12Q1/MCD12Q1.A2003001.h12v04.061.2022151161906.hdf"
#> [4] "./modis/MCD12Q1/MCD12Q1.A2004001.h12v04.061.2022152043252.hdf"
#> [5] "./modis/MCD12Q1/MCD12Q1.A2005001.h12v04.061.2022152140219.hdf"
#> [6] "./modis/MCD12Q1/MCD12Q1.A2006001.h12v04.061.2022202151028.hdf"
```

Examining the `files` object, we can see it is a character vector containing the paths to all downloaded files. All downloaded files can be found at the path specified using the argument `dl_path` and are in .hdf format, each file containing raster data for one MODIS tile for one of each requested year. These files can be brought into R using `terra::rast()` to examine, but we will use `landcover_extract()` to manage the extraction process.

# 2.3 Extracting landcover data with `landcover_extract()` {#2.3extract}

Once we have gathered the appropriate MODIS landcover data files, using `landcover_download()` or otherwise, we will want to extract the appropriate values and match them to our observations. Traditionally this might be accomplished with complicated for-loops running through each observation and matching it to the appropriate tile and year. Again, this would take significant time for the researcher and could be prone to errors for those not experienced with spatial operations in R. In these cases, `landcover_extract()` can help make the process quicker and easier.

This function works slightly differently depending on whether the input site data are in point or polygon format (again, either `sf` or `terra` objects are accepted). For point data, the extraction process will return the landcover category that each site point falls within in a column named `LC_TypeX_Class` (where X is the number associated with the selected landcover classification scheme). This is carried out via a call to `terra::extract()`. For polygon data, the extraction process will return the percent of the polygon (for buffered points this means the proportion of the buffered area) that each landcover category takes up with a column for each class named `LC_TypeX_[Class Name]`. This is carried out via a call to `landscapemetrics::calculate_lsm()`

To execute these extractions, we need to select which scheme we want to use, and specify it in the `covariates` argument. The appropriate covariate codes can be found in the `covariate_name` column of the table called with `nc_covariate_table()`. We will use the Leaf Area Index scheme, which is called by setting `covariates = "modis_lctype3"`. We will need to point `landcover_extract()` to where our MODIS data files are stored by providing a character vector with the filepaths of all applicable files to the argument `landcover_files`. Conveniently, this is exactly the output of `landcover_download()` that we stored in our `files` object.

``` r
# We will start by fetching the landcover data for our point dataset created above.
output <- landcover_extract(data = formatted,
                            covariates = "modis_lctype3",
                            landcover_files = files)
#> Warning: [MODIS Landcover Extraction]: MODIS data not available for 1978, 1979, 1980, 1981, 1982,
#> 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998,
#> 1999, 2000 - using data from nearest year(s) (2001).
#> [MODIS Landcover Extraction] calculating MODIS LC Type3.
```

Woah! That's a lot of warnings. These warnings are ultimately harmless but are important to consider. The MODIS Landcover dataset only extends back to 2001, and our data contains observations from before 2001. So, the function has grabbed the closest data point in time it can to those pre-2001 observations (the landcover category from 2001) and provides that instead. If we don't want this behaviour, we could go into our output data and manually set them to `NA` after running `landcover_extract()` using `output$LC_Type3_Class[output$survey_year < 2001] <- NA` . For this demonstration, we will leave it as is. This could also happen for observations in the current year (at the time of writing, 2026) as the MODIS landcover data available in a given year usually ends at the previous calendar year. In this case, the function would fetch the landcover category from the previous year and warn the user.

Let's take a look at what the function has returned for us!

``` r
head(output)
#> Simple feature collection with 6 features and 7 fields
#> Geometry type: POINT
#> Dimension:     XY
#> Bounding box:  xmin: 1426543 ymin: 792053.4 xmax: 1473174 ymax: 841722.6
#> Projected CRS: Canada_Albers_Equal_Area_Conic
#>   SurveyAreaIdentifier latitude longitude survey_year survey_month survey_day
#> 1    FilledSurveyArea1 45.51110 -77.50533        2011            2         12
#> 2    FilledSurveyArea2 45.63436 -77.07484        2010            7          3
#> 3    FilledSurveyArea3 45.82732 -77.12012        2010            6         19
#> 4    FilledSurveyArea4 45.48730 -77.74651        2011            5          5
#> 5    FilledSurveyArea5 45.61956 -77.23577        2010            6         16
#> 6    FilledSurveyArea6 45.82851 -77.11430        2011           10          2
#>                   geometry              LC_Type3_Class
#> 1 POINT (1444206 799722.4) deciduous_broadleaf_forests
#> 2 POINT (1473174 822088.3)                    savannas
#> 3 POINT (1463861 841469.8)         urban_builtup_lands
#> 4 POINT (1426543 792053.4) deciduous_broadleaf_forests
#> 5 POINT (1461424 817010.6) deciduous_broadleaf_forests
#> 6 POINT (1464264 841722.6)         urban_builtup_lands

table(output$LC_Type3_Class)
#> 
#>  deciduous_broadleaf_forests evergreen_needleleaf_forests                   grasslands 
#>                           43                            2                            5 
#>                     savannas          urban_builtup_lands                 water_bodies 
#>                           87                           16                            4
```

Now let's give it a go with polygon input data. We'll buffer our points to summarize landcover within a 500 m radius of each observation. We will expect and ignore the same warnings as in the previous example.

``` r
buffered <- data_buff(data = formatted)
#> [Data Buffering] buffering sites by 500m radius (default).

output <- landcover_extract(data = buffered,
                            covariates = "modis_lctype3",
                            landcover_files = files)
#> Warning: [MODIS Landcover Extraction]: MODIS data not available for 1978, 1979, 1980, 1981, 1982,
#> 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998,
#> 1999, 2000 - using data from nearest year(s) (2001).
#> [MODIS Landcover Extraction] calculating MODIS LC Type3.

head(output)
#> Simple feature collection with 6 features and 18 fields
#> Geometry type: POLYGON
#> Dimension:     XY
#> Bounding box:  xmin: 1426043 ymin: 791553.4 xmax: 1473674 ymax: 842222.6
#> Projected CRS: Canada_Albers_Equal_Area_Conic
#>   SurveyAreaIdentifier latitude longitude survey_year survey_month survey_day
#> 1    FilledSurveyArea1 45.51110 -77.50533        2011            2         12
#> 2    FilledSurveyArea2 45.63436 -77.07484        2010            7          3
#> 3    FilledSurveyArea3 45.82732 -77.12012        2010            6         19
#> 4    FilledSurveyArea4 45.48730 -77.74651        2011            5          5
#> 5    FilledSurveyArea5 45.61956 -77.23577        2010            6         16
#> 6    FilledSurveyArea6 45.82851 -77.11430        2011           10          2
#>                         geometry LC_Type3_water_bodies LC_Type3_grasslands LC_Type3_shrublands
#> 1 POLYGON ((1444706 799722.4,...               0.00000                   0                   0
#> 2 POLYGON ((1473674 822088.3,...               0.00000                   0                   0
#> 3 POLYGON ((1464361 841469.8,...              22.22222                   0                   0
#> 4 POLYGON ((1427043 792053.4,...               0.00000                   0                   0
#> 5 POLYGON ((1461924 817010.6,...               0.00000                   0                   0
#> 6 POLYGON ((1464764 841722.6,...              33.33333                   0                   0
#>   LC_Type3_broadleaf_croplands LC_Type3_savannas LC_Type3_evergreen_broadleaf_forests
#> 1                            0           0.00000                                    0
#> 2                            0          50.00000                                    0
#> 3                            0          11.11111                                    0
#> 4                            0           0.00000                                    0
#> 5                            0           0.00000                                    0
#> 6                            0           0.00000                                    0
#>   LC_Type3_deciduous_broadleaf_forests LC_Type3_evergreen_needleleaf_forests
#> 1                            100.00000                               0.00000
#> 2                             50.00000                               0.00000
#> 3                              0.00000                               0.00000
#> 4                             66.66667                              33.33333
#> 5                            100.00000                               0.00000
#> 6                              0.00000                               0.00000
#>   LC_Type3_deciduous_needleleaf_forests LC_Type3_nonvegetated_lands LC_Type3_urban_builtup_lands
#> 1                                     0                     0.00000                      0.00000
#> 2                                     0                     0.00000                      0.00000
#> 3                                     0                     0.00000                     66.66667
#> 4                                     0                     0.00000                      0.00000
#> 5                                     0                     0.00000                      0.00000
#> 6                                     0                    16.66667                     50.00000
#>   LC_Type3_unclassified
#> 1                     0
#> 2                     0
#> 3                     0
#> 4                     0
#> 5                     0
#> 6                     0
```

We can see that we have gained a number of columns, each with the percentage of the buffered area that is taken up by each particular class.

# 2.4 Tips and tricks

For users using data in non-BMDE formats (the default column-set downloaded via NatureCounts), alternate column names for your site names and year data can be provided directly to `landcover_download()` and `landcover_extract()` via the `site_name` and `date_year` columns. If you have already provided this information in a call to `data_fmt()` and are providing the output of that function as the `data` argument of either landcover function, you do not need to specify this information again.

By default, the MODIS files downloaded will be retained until the user manually deletes them. However, if the user wishes to save disk space and reduce clutter, the files can be automatically deleted by setting `retain = FALSE` in `landcover_extract()`.

Once you've extracted your landcover data, you may want to merge it back into the data you originally supplied to the `data` argument of `data_fmt()`. You can do so using `nc_covariates_merge()`.

**Congratulations!** You have now learned how to quickly download and extract the appropriate landcover data for your observation data using `landcover_download()` and `landcover_extract()`.
