---
title: "Chapter 5 - Downloading and Extracting WorldClim Data"
author: "Rory Macklin"
date: "2026-06-14"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Chapter 5 - Downloading and Extracting WorldClim Data}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---



# Chapter 5: Downloading and Extracting WorldClim Data

##### Author: Rory Macklin

> Climate norms can determine species' distributions by modulating the availability of particular habitat types, but also by exerting physiological pressure on species. Though climate norms are shifting, historical norms can be useful with older species occurence data, or as a point of comparison to current or future predicted conditions.

This tutorial assumes you have a basic understanding of working with spatial data in R. For a good introduction to these kinds of operations, the [NatureCounts Spatial Data Tutorial](https://github.com/BirdsCanada/NatureCounts_SpatialData_Tutorial) can serve as a useful starting point. It explains how to download, process, and visualize spatial data, including NatureCounts surveys, conservation areas, and environmental layers. This tutorial also uses functions demonstrated in [**Chapter 1: Formatting Data for Covariate Download and Extraction**](4.1-CovariateFormatting.html). If you are unfamiliar with these functions, we recommend using the previous tutorial to learn to conform your data to a standardized format used in WorldClim data download and extraction functions.

# 5.0 Learning Objectives

By the end of **Chapter 5 - Downloading and Extracting WorldClim Data**, users will:

- Have a basic understanding of the WorldClim dataset accessed through `worldclim_download()` and `worldclim_extract()`: [WorldClim data](#5.1worldclim).
- Be able to use `worldclim_download()` to download Worldclim data ready to match to observations in your data: [Downloading WorldClim data with `worldclim_download()`](#5.2download).
- Be able to use `worldclim_extract()` to extract and summarize WorldClim data for each observation in their data: [Extracting WorldClim data with `worldclim_extract()`](#5.3extract).

This R tutorial requires the following packages:


``` r
library(naturecounts)
library(tidyverse)
library(sf)
library(terra)
```

# 5.1 WorldClim data {#5.1worldclim}

The [WorldClim dataset](https://www.worldclim.org/) is a global dataset of gridded climatic data at a ~ 1 km resolution, with the monthly average from 1970-2000 available for several climatic variables. The variables available through `naturecounts` include:

- Average temperature (°C)
- Average minimum temperature (°C)
- Average maximum temperature (°C)
- Average total precipitation (mm)
- Average incident solar radiation (kJ/m^2/day)
- Average wind speed (2 m above the ground; m/s)

These average values are modeled from weather station data interpolated using satellite data such as elevation and surface temperature. For more information about the generation of this dataset, see [Fick & Hijmans (2017)](https://doi.org/10.1002/joc.5086).

# 5.2 Downloading WorldClim data with `worldclim_download()` {#5.2download}

WorldClim data can be accessed from their [website](https://www.worldclim.org/). While these are easily accessible, the entire global dataset is downloaded at once, making filesizes large, even if only a smaller area of data is needed. Thankfully, various R packages have allowed for reduced areas to be downloaded.

The R Package [`geodata`](https://github.com/rspatial/geodata) provides easy access to a number of geographic datasets within R, including the WorldClim dataset. In `worldclim_download()`, we employ functions from `geodata` and add quality of life features to further automate the downloading of WorldClim data.

First, lets prep some data from NatureCounts for use in downloading WorldClim data using `data_fmt()`. `worldclim_download()` reduces the required download from the global dataset to just the national dataset(s) required. This function needs input data in either `sf` or `terra` spatial format or can be called without input data if the country name(s) for data to be downloaded for is provided. If providing input spatial data, you can provide your own data in the required format, or use the built-in `naturecounts::data_fmt()` function to conform your data to the necessary format.


``` r
# This dataset containing Black-capped Chickadee observations included in
# the naturecounts R package is in a data.frame format, and contains the columns
# we need (latitude, longitude, and month)!
# We'll need to to convert it into an sf object for use in worldclim_download().
bcch %>%
  select(latitude, longitude, survey_month) %>%
  head()
#>   latitude longitude survey_month
#> 1 45.81553 -77.14251           11
#> 2 45.81553 -77.14251           12
#> 3 45.55757 -77.41739           12
#> 4 45.55757 -77.41739           12
#> 5 45.79170 -76.90276            4
#> 6 45.79170 -76.90276            4

# We can make a call to data_fmt() to automatically convert this to an sf object
# ready to work with naturecounts' covariate download and extraction functions. We
# can ignore the warning as EPSG:4326 is an appropriate CRS for our data.
formatted <- data_fmt(bcch)
#> [Data Formatting] beginning formatting.
#> Warning: [Data Formatting] as the 'crs' argument is not specified, data CRS is assumed to be
#> EPSG:4326.

head(formatted)
#> Simple feature collection with 6 features and 6 fields
#> Geometry type: POINT
#> Dimension:     XY
#> Bounding box:  xmin: 1449503 ymin: 806527.6 xmax: 1481359 ymax: 842474.9
#> Projected CRS: Canada_Albers_Equal_Area_Conic
#>   SurveyAreaIdentifier latitude longitude survey_year survey_month survey_day
#> 1    FilledSurveyArea1 45.81553 -77.14251        1999           11         18
#> 2    FilledSurveyArea1 45.81553 -77.14251        2000           12         16
#> 3    FilledSurveyArea2 45.55757 -77.41739        1999           12         19
#> 4    FilledSurveyArea2 45.55757 -77.41739        2000           12         19
#> 5    FilledSurveyArea3 45.79170 -76.90276        2000            4         15
#> 6    FilledSurveyArea3 45.79170 -76.90276        1999            4         17
#>                   geometry
#> 1 POINT (1462530 839736.7)
#> 2 POINT (1462530 839736.7)
#> 3 POINT (1449503 806527.6)
#> 4 POINT (1449503 806527.6)
#> 5 POINT (1481359 842474.9)
#> 6 POINT (1481359 842474.9)
```
With our data prepared, we can make a call to `worldclim_download()` to begin downloading WorldClim data. If we provide the spatial data we have generated, `worldclim_download()` will attempt to identify the country or countries that the data falls within. Since all of our test data falls within Canada, we could provide the country name "Canada" or the [ISO3 code](https://en.wikipedia.org/wiki/ISO_3166-1_alpha-3) "CAN" to the `countries` argument instead of our input data and achieve the same result.

At this stage, we also need to decide which climatic variables we want to download. We can provide the following names to the `covariates` argument to download one or multiple datasets:

- `worldclim_tavg` - average temperature (°C)
- `worldclim_tmin` - average minimum temperature (°C)
- `worldclim_tmax` - average maximum temperature (°C)
- `worldclim_prec` - average total precipitation (mm)
- `worldclim_srad` - average incident solar radiation (kJ/m^2/day)
- `worldclim_wind` - average wind speed (2 m above the ground; m/s)

We will download the minimum and maximum temperature datasets.


``` r
# Let's download some files! Files will be downloaded into a 'worldclim/' subdirectory in your current working directory.

climate_data <- worldclim_download(data = formatted,
                                   covariates = c("worldclim_tmax", "worldclim_tmin"))
                            
climate_data
#> $tmax
#> class       : SpatRaster
#> size        : 5040, 10680, 12  (nrow, ncol, nlyr)
#> resolution  : 0.008333333, 0.008333333  (x, y)
#> extent      : -141.5, -52.5, 41.5, 83.5  (xmin, xmax, ymin, ymax)
#> coord. ref. : lon/lat WGS 84 (EPSG:4326)
#> source      : CAN_wc2.1_30s_tmax.tif
#> names       : CAN_w~max_1, CAN_w~max_2, CAN_w~max_3, CAN_w~max_4, CAN_w~max_5, CAN_w~max_6, ...
#> min values  :  -38.599998,       -40.5,  -39.099998,       -30.6,       -21.1,       -14.6, ...
#> max values  :        13.2,        13.9,        15.9,   20.200001,        26.6,   31.799999, ...
#> 
#> $tmin
#> class       : SpatRaster
#> size        : 5040, 10680, 12  (nrow, ncol, nlyr)
#> resolution  : 0.008333333, 0.008333333  (x, y)
#> extent      : -141.5, -52.5, 41.5, 83.5  (xmin, xmax, ymin, ymax)
#> coord. ref. : lon/lat WGS 84 (EPSG:4326)
#> source      : CAN_wc2.1_30s_tmin.tif
#> names       : CAN_w~min_1, CAN_w~min_2, CAN_w~min_3, CAN_w~min_4, CAN_w~min_5, CAN_w~min_6, ...
#> min values  :  -46.099998,  -47.799999,  -47.599998,  -38.799999,  -23.799999,  -17.700001, ...
#> max values  :         5.8,         5.7,           6,         6.7,        10.8,   16.299999, ...
```

Examining the `climate_data` object, we can see it is a list containing two `terra::SpatRaster` containing our requested data for Canada. All downloaded files can be found by default in the created `./worldclim` subdirectory or at a custom path specified using the argument `dl_path`. Files are in .tif format, with each file containing raster data for one of the requested countries, with a layer containing the reqeuested climate variables for each month. The `SpatRaster` output by `worldclim_download()` is a merged representation of these files.

# 5.3 Extracting WorldClim data with `worldclim_extract()` {#5.3extract}

Once we have gathered the appropriate WorldClim data rasters, using `worldclim_download()` or otherwise, we will want to extract the appropriate values and match them to our observations. Traditionally this might be accomplished with complicated for-loops running through each observation and matching it to the appropriate country file and month. This could take significant time for the researcher and could be prone to errors for those not experienced with spatial operations in R. In these cases, `worldclim_extract()` can help make the process quicker and easier.

This function works slightly differently depending on whether the input site data are in point or polygon format (again, either `sf` or `terra` objects are accepted). For point data, the extraction process will return the climate variable value of the raster grid cell that each site point falls within for the appropriate month in a column named following the abbreviated name of that variable (e.g., `tmax`). This is carried out via a call to `terra::extract()`. For polygon data, the extraction process will return the mean climate variable value of cells overlapped by each polygon for the appropriate month, again in a column named following the variable's abbreviated name. This is carried out via a call to `exactextractr::exact_extract()`.

The input data must also have a column containing the month in which each observation was made. By default, `worldclim_extract()` searches for this information in the BMDE column `survey_month` (included by default in data downloaded through `naturecounts`), but alternate month column names can be specified using the `date_month` argument.

To execute these extractions, we will need to point `worldclim_extract()` to the object containing our WorldClim data using the argument `worldclim_data`. Conveniently, this object is exactly the output of `worldclim_download()` that we stored in our `climate_data` object.


``` r
# We will start by fetching the WorldClim data for our point dataset created above.
output <- worldclim_extract(data = formatted,
                            covariates = c("worldclim_tmax", "worldclim_tmin"),
                            worldclim_data = climate_data)
#> [WorldClim Extraction] extracting WorldClim tmax.
#> [WorldClim Extraction] extracting WorldClim tmin.

head(output)
#> Simple feature collection with 6 features and 8 fields
#> Geometry type: POINT
#> Dimension:     XY
#> Bounding box:  xmin: 1449503 ymin: 806527.6 xmax: 1481359 ymax: 842474.9
#> Projected CRS: Canada_Albers_Equal_Area_Conic
#>   SurveyAreaIdentifier latitude longitude survey_year survey_month survey_day
#> 1    FilledSurveyArea1 45.81553 -77.14251        1999           11         18
#> 2    FilledSurveyArea1 45.81553 -77.14251        2000           12         16
#> 3    FilledSurveyArea2 45.55757 -77.41739        1999           12         19
#> 4    FilledSurveyArea2 45.55757 -77.41739        2000           12         19
#> 5    FilledSurveyArea3 45.79170 -76.90276        2000            4         15
#> 6    FilledSurveyArea3 45.79170 -76.90276        1999            4         17
#>                   geometry tmax  tmin
#> 1 POINT (1462530 839736.7)  4.9  -2.9
#> 2 POINT (1462530 839736.7) -2.9 -12.1
#> 3 POINT (1449503 806527.6) -2.6 -12.1
#> 4 POINT (1449503 806527.6) -2.6 -12.1
#> 5 POINT (1481359 842474.9)  9.1  -2.0
#> 6 POINT (1481359 842474.9)  9.1  -2.0
```

Now let's give it a go with polygon input data. We'll buffer our points to fetch the mean average maximum and minimum montly temperature within a 500 m radius of each observation.


``` r
buffered <- data_buff(data = formatted)
#> [Data Buffering] buffering sites by 500m radius (default).

output <- worldclim_extract(data = buffered,
                            covariates = c("worldclim_tmax", "worldclim_tmin"),
                            worldclim_data = climate_data)
#> [WorldClim Extraction] extracting WorldClim tmax.
#> [WorldClim Extraction] extracting WorldClim tmin.

head(output)
#> Simple feature collection with 6 features and 8 fields
#> Geometry type: POLYGON
#> Dimension:     XY
#> Bounding box:  xmin: 1449003 ymin: 806027.6 xmax: 1481859 ymax: 842974.9
#> Projected CRS: Canada_Albers_Equal_Area_Conic
#>   SurveyAreaIdentifier latitude longitude survey_year survey_month survey_day
#> 1    FilledSurveyArea1 45.81553 -77.14251        1999           11         18
#> 2    FilledSurveyArea1 45.81553 -77.14251        2000           12         16
#> 3    FilledSurveyArea2 45.55757 -77.41739        1999           12         19
#> 4    FilledSurveyArea2 45.55757 -77.41739        2000           12         19
#> 5    FilledSurveyArea3 45.79170 -76.90276        2000            4         15
#> 6    FilledSurveyArea3 45.79170 -76.90276        1999            4         17
#>                         geometry      tmax       tmin
#> 1 POLYGON ((1463030 839736.7,...  4.968483  -2.797274
#> 2 POLYGON ((1463030 839736.7,... -2.831517 -12.031516
#> 3 POLYGON ((1450003 806527.6,... -2.583323 -12.083324
#> 4 POLYGON ((1450003 806527.6,... -2.583323 -12.083324
#> 5 POLYGON ((1481859 842474.9,...  9.096169  -2.025829
#> 6 POLYGON ((1481859 842474.9,...  9.096169  -2.025829
```

We can see that the mean minimum and maximum temperature values have been added in the `tmax` and `tmin` column.

# 5.4 Tips and tricks

For users using data in non-BMDE formats (the default column-set downloaded via NatureCounts), alternate column names for your site names and month data can be provided directly to `worldclim_download()` and `worldclim_extract()` via the `site_name` and `date_month` argument respectively. If you have already provided this information in a call to `data_fmt()` and are providing the output of that function as the `data` argument of either `worldclim_` function, you do not need to specify this information again.

By default, the WorldClim files downloaded will be retained until the user manually deletes them. However, if the user wishes to save disk space and reduce clutter, the files can be automatically deleted by setting `retain = FALSE` in `worldclim_extract()`.

Once you've extracted your WorldClim data, you may want to merge it back into the data you originally supplied to the `data` argument of `data_fmt()`. You can do so using `nc_covariates_merge()`.

**Congratulations!** You have now learned how to quickly download and extract the appropriate WorldClim data for your observation data using `worldclim_download()` and `worldclim_extract()`.
