<!DOCTYPE html>
<!-- Generated by pkgdown: do not edit by hand --><html lang="en">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Mapping Observations • naturecounts</title>
<!-- jquery --><script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script><!-- Bootstrap --><link href="https://cdnjs.cloudflare.com/ajax/libs/bootswatch/3.4.0/sandstone/bootstrap.min.css" rel="stylesheet" crossorigin="anonymous">
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.4.1/js/bootstrap.min.js" integrity="sha256-nuL8/2cJ5NDSSwnKD8VqreErSWHtnEP9E7AySL+1ev4=" crossorigin="anonymous"></script><!-- bootstrap-toc --><link rel="stylesheet" href="../../bootstrap-toc.css">
<script src="../../bootstrap-toc.js"></script><!-- Font Awesome icons --><link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/all.min.css" integrity="sha256-mmgLkCYLUQbXn0B1SRqzHar6dCnv9oZFPEC1g1cwlkk=" crossorigin="anonymous">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.12.1/css/v4-shims.min.css" integrity="sha256-wZjR52fzng1pJHwx4aV2AO3yyTOXrcDW7jBpJtTwVxw=" crossorigin="anonymous">
<!-- clipboard.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/clipboard.js/2.0.6/clipboard.min.js" integrity="sha256-inc5kl9MA1hkeYUt+EC3BhlIgyp/2jDIyBLS6k3UxPI=" crossorigin="anonymous"></script><!-- headroom.js --><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/headroom.min.js" integrity="sha256-AsUX4SJE1+yuDu5+mAVzJbuYNPHj/WroHuZ8Ir/CkE0=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/headroom/0.11.0/jQuery.headroom.min.js" integrity="sha256-ZX/yNShbjqsohH1k95liqY9Gd8uOiE1S4vZc+9KQ1K4=" crossorigin="anonymous"></script><!-- pkgdown --><link href="../../pkgdown.css" rel="stylesheet">
<script src="../../pkgdown.js"></script><link href="../../extra.css" rel="stylesheet">
<meta property="og:title" content="Mapping Observations">
<meta property="og:description" content="naturecounts">
<!-- mathjax --><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/MathJax.js" integrity="sha256-nvJJv9wWKEm88qvoQl9ekL2J+k/RWIsaSScxxlsrv8k=" crossorigin="anonymous"></script><script src="https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.5/config/TeX-AMS-MML_HTMLorMML.js" integrity="sha256-84DKXVJXs0/F8OTMzX4UR909+jtl4G7SPypPavF+GfA=" crossorigin="anonymous"></script><!--[if lt IE 9]>
<script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body data-spy="scroll" data-target="#toc">
    <div class="container template-article">
      <header><div class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <span class="navbar-brand">
        <a class="navbar-link" href="../../index.html">naturecounts</a>
        <span class="version label label-danger" data-toggle="tooltip" data-placement="bottom" title="Unreleased version">0.2.2</span>
      </span>
    </div>

    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav">
<li>
  <a href="../../index.html">
    <span class="fas fa-home"></span>
     
  </a>
</li>
<li>
  <a href="../../reference/index.html">Reference</a>
</li>
<li>
  <a href="../../articles/index.html">Articles</a>
</li>
<li>
  <a href="../../news/index.html">News</a>
</li>
      </ul>
<ul class="nav navbar-nav navbar-right">
<li>
  <a href="https://github.com/BirdStudiesCanada/naturecounts">
    <span class="fas fa-github fa-lg"></span>
     
  </a>
</li>
      </ul>
</div>
<!--/.nav-collapse -->
  </div>
<!--/.container -->
</div>
<!--/.navbar -->

      

      </header><script src="mapping-observations_files/header-attrs-2.6/header-attrs.js"></script><div class="row">
  <div class="col-md-9 contents">
    <div class="page-header toc-ignore">
      <h1 data-toc-skip>Mapping Observations</h1>
            
            <h4 class="date">2021-03-02</h4>
      
      <small class="dont-index">Source: <a href="https://github.com/BirdStudiesCanada/naturecounts/blob/master/vignettes/articles/mapping-observations.Rmd"><code>vignettes/articles/mapping-observations.Rmd</code></a></small>
      <div class="hidden name"><code>mapping-observations.Rmd</code></div>

    </div>

    
    
<p>In this article we’ll walk through how to create various types of maps of the observations downloaded with <code>naturecounts</code> to get a sense of the spatial distribution.</p>
<blockquote>
<p>The following examples use the “testuser” user which is not available to you. You can quickly <a href="https://www.birdscanada.org/birdmon/default/register.jsp">sign up for a free account</a> of your own to access and play around with these examples.</p>
</blockquote>
<div id="setup" class="section level2">
<h2 class="hasAnchor">
<a href="#setup" class="anchor"></a>Setup</h2>
<p>To do so we’re going to use the following packages:</p>
<div class="sourceCode" id="cb1"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/BirdStudiesCanada/naturecounts">naturecounts</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://r-spatial.github.io/sf/">sf</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/ropenscilabs/rnaturalearth">rnaturalearth</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/dkahle/ggmap">ggmap</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://dplyr.tidyverse.org">dplyr</a></span><span class="op">)</span>
<span class="kw"><a href="https://rdrr.io/r/base/library.html">library</a></span><span class="op">(</span><span class="va"><a href="https://github.com/r-spatial/mapview">mapview</a></span><span class="op">)</span></code></pre></div>
<p>First we’ll use download some data:</p>
<div class="sourceCode" id="cb2"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">barred_owls</span> <span class="op">&lt;-</span> <span class="fu"><a href="../../reference/nc_data_dl.html">nc_data_dl</a></span><span class="op">(</span>species <span class="op">=</span> <span class="fl">7590</span>, region <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/list.html">list</a></span><span class="op">(</span>statprov <span class="op">=</span> <span class="st">"AB"</span><span class="op">)</span>, 
                          username <span class="op">=</span> <span class="st">"testuser"</span>, info <span class="op">=</span> <span class="st">"nc_tutorial"</span><span class="op">)</span></code></pre></div>
<pre><code>## Using filters: species (7590); fields_set (BMDE2.00-min); statprov (AB)</code></pre>
<pre><code>## Collecting available records...</code></pre>
<pre><code>##   collection nrecords
## 1   ABATLAS1       70
## 2   ABATLAS2      103
## 3 ABBIRDRECS      202
## 4        BBS        8
## 5  BBS50-CAN        8
## 6        PFW        5
## Total records: 396</code></pre>
<pre><code>## 
## Downloading records for each collection:</code></pre>
<pre><code>##   ABATLAS1</code></pre>
<pre><code>##     Records 1 to 70 / 70</code></pre>
<pre><code>##   ABATLAS2</code></pre>
<pre><code>##     Records 1 to 103 / 103</code></pre>
<pre><code>##   ABBIRDRECS</code></pre>
<pre><code>##     Records 1 to 202 / 202</code></pre>
<pre><code>##   BBS</code></pre>
<pre><code>##     Records 1 to 8 / 8</code></pre>
<pre><code>##   BBS50-CAN</code></pre>
<pre><code>##     Records 1 to 8 / 8</code></pre>
<pre><code>##   PFW</code></pre>
<pre><code>##     Records 1 to 5 / 5</code></pre>
<div class="sourceCode" id="cb19"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">barred_owls</span><span class="op">)</span></code></pre></div>
<pre><code>##   record_id collection project_id protocol_id protocol_type species_id
## 1 225604466   ABATLAS1       1048          NA            NA       7590
## 2 225604642   ABATLAS1       1048          NA            NA       7590
## 3 225610784   ABATLAS1       1048          NA            NA       7590
## 4 225611808   ABATLAS1       1048          NA            NA       7590
## 5 225616490   ABATLAS1       1048          NA            NA       7590
## 6 225617764   ABATLAS1       1048          NA            NA       7590
##   statprov_code country_code SiteCode latitude longitude bcr subnational2_code
## 1            AB           CA     2681 58.32639 -116.4019   6          CA.AB.17
## 2            AB           CA     6270 58.23722 -111.4258   6          CA.AB.16
## 3            AB           CA     3367 54.53889 -115.0678   6          CA.AB.17
## 4            AB           CA     1251 53.83417 -117.5319   6          CA.AB.14
## 5            AB           CA     2988 51.03000 -114.9319  10          CA.AB.15
## 6            AB           CA     1251 53.83417 -117.5319   6          CA.AB.14
##   iba_site utm_square survey_year survey_month survey_week survey_day
## 1      N/A    11VNE36        1990            6           2          9
## 2      N/A    12VVK75        1991            6           3         17
## 3      N/A    11UPA24        1991           NA          NA         NA
## 4      N/A    11UMV66        1990            5           1          7
## 5      N/A    11UPS45        1991           NA          NA         NA
## 6      N/A    11UMV66        1990            5           2          9
##   breeding_rank                GlobalUniqueIdentifier CatalogNumber Locality
## 1            10 URN:NatureAlberta:ABATLAS1:I4017-BAOW    I4017-BAOW  11UNQ36
## 2            10 URN:NatureAlberta:ABATLAS1:J5005-BAOW    J5005-BAOW  12UVV75
## 3             0 URN:NatureAlberta:ABATLAS1:G5031-BAOW    G5031-BAOW  11UPL24
## 4            60 URN:NatureAlberta:ABATLAS1:F4057-BAOW    F4057-BAOW  11UMK66
## 5             0 URN:NatureAlberta:ABATLAS1:C5136-BAOW    C5136-BAOW  11UPG45
## 6            10 URN:NatureAlberta:ABATLAS1:F4033-BAOW    F4033-BAOW  11UMK66
##   TimeCollected CollectorNumber FieldNumber Remarks ProjectCode
## 1          &lt;NA&gt;            1728          NA    &lt;NA&gt;    ABATLAS1
## 2          &lt;NA&gt;            1718          NA    &lt;NA&gt;    ABATLAS1
## 3          &lt;NA&gt;            1760          NA    &lt;NA&gt;    ABATLAS1
## 4          &lt;NA&gt;            1710          NA    &lt;NA&gt;    ABATLAS1
## 5          &lt;NA&gt;            1375          NA    &lt;NA&gt;    ABATLAS1
## 6          &lt;NA&gt;            1248          NA    &lt;NA&gt;    ABATLAS1
##          ProtocolType ProtocolCode ProtocolURL SurveyAreaIdentifier
## 1 Breeding Bird Atlas         &lt;NA&gt;        &lt;NA&gt;                 2681
## 2 Breeding Bird Atlas         &lt;NA&gt;        &lt;NA&gt;                 6270
## 3 Breeding Bird Atlas         &lt;NA&gt;        &lt;NA&gt;                 3367
## 4 Breeding Bird Atlas         &lt;NA&gt;        &lt;NA&gt;                 1251
## 5 Breeding Bird Atlas         &lt;NA&gt;        &lt;NA&gt;                 2988
## 6 Breeding Bird Atlas         &lt;NA&gt;        &lt;NA&gt;                 1251
##   SamplingEventIdentifier SamplingEventStructure RouteIdentifier
## 1                   I4017                     NA            &lt;NA&gt;
## 2                   J5005                     NA            &lt;NA&gt;
## 3                   G5031                     NA            &lt;NA&gt;
## 4                   F4057                     NA            &lt;NA&gt;
## 5                   C5136                     NA            &lt;NA&gt;
## 6                   F4033                     NA            &lt;NA&gt;
##   TimeObservationsStarted TimeObservationsEnded DurationInHours
## 1                    &lt;NA&gt;                  &lt;NA&gt;            &lt;NA&gt;
## 2                    &lt;NA&gt;                  &lt;NA&gt;            &lt;NA&gt;
## 3                    &lt;NA&gt;                  &lt;NA&gt;            &lt;NA&gt;
## 4                    &lt;NA&gt;                  &lt;NA&gt;            &lt;NA&gt;
## 5                    &lt;NA&gt;                  &lt;NA&gt;            &lt;NA&gt;
## 6                    &lt;NA&gt;                  &lt;NA&gt;            &lt;NA&gt;
##   TimeIntervalStarted TimeIntervalEnded TimeIntervalsAdditive NumberOfObservers
## 1                  NA                NA                    NA                 1
## 2                  NA                NA                    NA                 3
## 3                  NA                NA                    NA                 0
## 4                  NA                NA                    NA                 0
## 5                  NA                NA                    NA                 0
## 6                  NA                NA                    NA                 2
##   NoObservations ObservationCount ObservationDescriptor ObservationCount2
## 1             NA             &lt;NA&gt;                  &lt;NA&gt;              &lt;NA&gt;
## 2             NA             &lt;NA&gt;                  &lt;NA&gt;              &lt;NA&gt;
## 3             NA             &lt;NA&gt;                  &lt;NA&gt;              &lt;NA&gt;
## 4             NA             &lt;NA&gt;                  &lt;NA&gt;              &lt;NA&gt;
## 5             NA             &lt;NA&gt;                  &lt;NA&gt;              &lt;NA&gt;
## 6             NA             &lt;NA&gt;                  &lt;NA&gt;              &lt;NA&gt;
##   ObservationDescriptor2 ObservationCount3 ObservationDescriptor3
## 1                   &lt;NA&gt;              &lt;NA&gt;                   &lt;NA&gt;
## 2                   &lt;NA&gt;              &lt;NA&gt;                   &lt;NA&gt;
## 3                   &lt;NA&gt;              &lt;NA&gt;                   &lt;NA&gt;
## 4                   &lt;NA&gt;              &lt;NA&gt;                   &lt;NA&gt;
## 5                   &lt;NA&gt;              &lt;NA&gt;                   &lt;NA&gt;
## 6                   &lt;NA&gt;              &lt;NA&gt;                   &lt;NA&gt;
##   ObservationCount4 ObservationDescriptor4 ObservationCount5
## 1              &lt;NA&gt;                   &lt;NA&gt;              &lt;NA&gt;
## 2              &lt;NA&gt;                   &lt;NA&gt;              &lt;NA&gt;
## 3              &lt;NA&gt;                   &lt;NA&gt;              &lt;NA&gt;
## 4              &lt;NA&gt;                   &lt;NA&gt;              &lt;NA&gt;
## 5              &lt;NA&gt;                   &lt;NA&gt;              &lt;NA&gt;
## 6              &lt;NA&gt;                   &lt;NA&gt;              &lt;NA&gt;
##   ObservationDescriptor5 ObservationCount6 ObservationDescriptor6
## 1                   &lt;NA&gt;              &lt;NA&gt;                   &lt;NA&gt;
## 2                   &lt;NA&gt;              &lt;NA&gt;                   &lt;NA&gt;
## 3                   &lt;NA&gt;              &lt;NA&gt;                   &lt;NA&gt;
## 4                   &lt;NA&gt;              &lt;NA&gt;                   &lt;NA&gt;
## 5                   &lt;NA&gt;              &lt;NA&gt;                   &lt;NA&gt;
## 6                   &lt;NA&gt;              &lt;NA&gt;                   &lt;NA&gt;
##   AllIndividualsReported AllSpeciesReported
## 1                   &lt;NA&gt;            Unknown
## 2                   &lt;NA&gt;            Unknown
## 3                   &lt;NA&gt;            Unknown
## 4                   &lt;NA&gt;            Unknown
## 5                   &lt;NA&gt;            Unknown
## 6                   &lt;NA&gt;            Unknown</code></pre>
</div>
<div id="simple-maps" class="section level2">
<h2 class="hasAnchor">
<a href="#simple-maps" class="anchor"></a>Simple Maps</h2>
<p>The quickest way to look at the spatial distribution is probably to use Stamen maps through the <code>ggmap</code> package.</p>
<p>First let’s get an idea of how many distinct points there are (often multiple observations are recorded for the same location).</p>
<div class="sourceCode" id="cb21"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="va">barred_owls</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 396</code></pre>
<div class="sourceCode" id="cb23"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://dplyr.tidyverse.org/reference/select.html">select</a></span><span class="op">(</span><span class="va">barred_owls</span>, <span class="va">longitude</span>, <span class="va">latitude</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/distinct.html">distinct</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/base/nrow.html">nrow</a></span><span class="op">(</span><span class="op">)</span></code></pre></div>
<pre><code>## [1] 259</code></pre>
<p>So we have 259 sites for 396 observations.</p>
<p>Next let’s convert our data to spatial data so we can extract the spatial extent. Note that we’re using CRS EPSG code of 4326 because that’s reflects unprojected, GPS data in lat/lon.</p>
<div class="sourceCode" id="cb25"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">barred_owls_sf</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_as_sf.html">st_as_sf</a></span><span class="op">(</span><span class="va">barred_owls</span>, 
                           coords <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"longitude"</span>, <span class="st">"latitude"</span><span class="op">)</span>, crs <span class="op">=</span> <span class="fl">4326</span><span class="op">)</span></code></pre></div>
<p>We can extract the spatial extent (<strong>b</strong>ounding <strong>box</strong>) with the <code><a href="https://r-spatial.github.io/sf/reference/st_bbox.html">st_bbox()</a></code> function.</p>
<div class="sourceCode" id="cb26"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_bbox.html">st_bbox</a></span><span class="op">(</span><span class="va">barred_owls_sf</span><span class="op">)</span></code></pre></div>
<pre><code>##       xmin       ymin       xmax       ymax 
## -119.50848   50.65669 -110.01704   58.32639</code></pre>
<p>Now we’re ready to make a map of the distribution of observations. First we get the baselayer map.</p>
<div class="sourceCode" id="cb28"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">map</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/ggmap/man/get_stamenmap.html">get_stamenmap</a></span><span class="op">(</span>bbox <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_bbox.html">st_bbox</a></span><span class="op">(</span><span class="va">barred_owls_sf</span><span class="op">)</span><span class="op">)</span>, zoom <span class="op">=</span> <span class="fl">5</span><span class="op">)</span></code></pre></div>
<pre><code>## Source : http://tile.stamen.com/terrain/5/5/9.png</code></pre>
<pre><code>## Source : http://tile.stamen.com/terrain/5/6/9.png</code></pre>
<pre><code>## Source : http://tile.stamen.com/terrain/5/5/10.png</code></pre>
<pre><code>## Source : http://tile.stamen.com/terrain/5/6/10.png</code></pre>
<p>Now we can add our observations. Note that for <code>ggmap</code>, we’ll use non-sf data frame.</p>
<div class="sourceCode" id="cb33"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/ggmap/man/ggmap.html">ggmap</a></span><span class="op">(</span><span class="va">map</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">geom_point</span><span class="op">(</span>data <span class="op">=</span> <span class="va">barred_owls</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">longitude</span>, y <span class="op">=</span> <span class="va">latitude</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p><img src="mapping-observations_files/figure-html/unnamed-chunk-7-1.png" width="700"></p>
<p>Let’s count our observations for each site.</p>
<div class="sourceCode" id="cb34"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/ggmap/man/ggmap.html">ggmap</a></span><span class="op">(</span><span class="va">map</span><span class="op">)</span> <span class="op">+</span> 
  <span class="fu">geom_count</span><span class="op">(</span>data <span class="op">=</span> <span class="va">barred_owls</span>, <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">longitude</span>, y <span class="op">=</span> <span class="va">latitude</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p><img src="mapping-observations_files/figure-html/unnamed-chunk-8-1.png" width="700"></p>
</div>
<div id="interactive-maps" class="section level2">
<h2 class="hasAnchor">
<a href="#interactive-maps" class="anchor"></a>Interactive Maps</h2>
<p>If we want to get fancy we can also create interactive maps using the <code>mapview</code> packages (see also the <a href="https://rstudio.github.io/leaflet/"><code>leaflet</code> for R package</a>).</p>
<div class="sourceCode" id="cb35"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/mapview/man/mapView.html">mapview</a></span><span class="op">(</span><span class="va">barred_owls_sf</span>, zcol <span class="op">=</span> <span class="st">"survey_year"</span>, at <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">1965</span>, <span class="fl">2005</span>, by <span class="op">=</span> <span class="fl">10</span><span class="op">)</span>,
        map.types <span class="op">=</span> <span class="st">"Esri.WorldImagery"</span><span class="op">)</span></code></pre></div>
</div>
<div id="more-complex-maps" class="section level2">
<h2 class="hasAnchor">
<a href="#more-complex-maps" class="anchor"></a>More Complex Maps</h2>
<p>For more complex, or detailed maps, we can use a variety of spatial data files to layer our data over maps of the area.</p>
<p>For this we’ll get some outlines of Canada and it’s Provinces and Territories from <code>rnaturalearth</code>.</p>
<div class="sourceCode" id="cb36"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">canada</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://rdrr.io/pkg/rnaturalearth/man/ne_states.html">ne_states</a></span><span class="op">(</span>country <span class="op">=</span> <span class="st">"canada"</span>, returnclass <span class="op">=</span> <span class="st">"sf"</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_transform.html">st_transform</a></span><span class="op">(</span><span class="fl">3347</span><span class="op">)</span>

<span class="fu">ggplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_sf</span><span class="op">(</span>data <span class="op">=</span> <span class="va">canada</span><span class="op">)</span></code></pre></div>
<p><img src="mapping-observations_files/figure-html/unnamed-chunk-10-1.png" width="700"></p>
<p>Let’s add our observations (note that the data are transformed to match the projection of the first layer, here the <code>canada</code> data).</p>
<div class="sourceCode" id="cb37"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">ggplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_sf</span><span class="op">(</span>data <span class="op">=</span> <span class="va">canada</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_sf</span><span class="op">(</span>data <span class="op">=</span> <span class="va">barred_owls_sf</span>, size <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span></code></pre></div>
<p><img src="mapping-observations_files/figure-html/unnamed-chunk-11-1.png" width="700"></p>
<p>We can also focus on Alberta</p>
<div class="sourceCode" id="cb38"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">ab</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">canada</span>, <span class="va">name</span> <span class="op">==</span> <span class="st">"Alberta"</span><span class="op">)</span>

<span class="fu">ggplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_sf</span><span class="op">(</span>data <span class="op">=</span> <span class="va">ab</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_sf</span><span class="op">(</span>data <span class="op">=</span> <span class="va">barred_owls_sf</span>, size <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span></code></pre></div>
<p><img src="mapping-observations_files/figure-html/unnamed-chunk-12-1.png" width="700"></p>
<p>Perhaps we should see how many of these observations were made in parks.</p>
<p>First we’ll download and extract the Park shapefiles available from the <a href="https://www.albertaparks.ca/albertaparksca/library/downloadable-data-sets/">Alberta Parks</a> website.</p>
<div class="sourceCode" id="cb39"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">url</span> <span class="op">&lt;-</span> <span class="st">"https://www.albertaparks.ca/media/2941843/parks_and_protected_areas_alberta.zip"</span>
<span class="fu"><a href="https://rdrr.io/r/utils/download.file.html">download.file</a></span><span class="op">(</span>url <span class="op">=</span> <span class="va">url</span><span class="op">)</span>
<span class="fu"><a href="https://rdrr.io/r/utils/unzip.html">unzip</a></span><span class="op">(</span><span class="st">"parks_and_protected_areas_alberta.zip"</span><span class="op">)</span>

<span class="va">parks</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_read.html">st_read</a></span><span class="op">(</span><span class="st">"Parks_Protected_Areas_Alberta.shp"</span><span class="op">)</span></code></pre></div>
<pre><code>## Reading layer `Parks_Protected_Areas_Alberta' from data source `/home/steffi/Projects/Business/BSC/NatureCounts/naturecounts/vignettes/articles/article_files/Parks_Protected_Areas_Alberta.shp' using driver `ESRI Shapefile'
## Simple feature collection with 477 features and 17 fields
## geometry type:  MULTIPOLYGON
## dimension:      XY
## bbox:           xmin: 170844.3 ymin: 5425575 xmax: 860845.9 ymax: 6659216
## projected CRS:  NAD83 / Alberta 10-TM (Forest)</code></pre>
<p>Add this layer to our plot.</p>
<div class="sourceCode" id="cb41"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">ggplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_sf</span><span class="op">(</span>data <span class="op">=</span> <span class="va">ab</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_sf</span><span class="op">(</span>data <span class="op">=</span> <span class="va">parks</span>, colour <span class="op">=</span> <span class="st">"darkgreen"</span>, fill <span class="op">=</span> <span class="st">"forestgreen"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_sf</span><span class="op">(</span>data <span class="op">=</span> <span class="va">barred_owls_sf</span>, size <span class="op">=</span> <span class="fl">0.5</span><span class="op">)</span></code></pre></div>
<p><img src="mapping-observations_files/figure-html/unnamed-chunk-16-1.png" width="700"></p>
<p>Well it’s actually a bit difficult to tell, there are lots of small parks!</p>
<p>To solve this problem, we can merge our observations with the parks and plot those inside parks separately from those outside parks.</p>
<p>First we’ll transform our observation data to match the CRS of <code>parks</code>, then we’ll join the park information to our observations, based on whether the observations overlap a park polygon (by default this is a left join), and finally we’ll create a new column <code>outside_park</code> that is a category for out or in the park, based on whether the observation was joined to a park name (<code>OC_NAME</code>).</p>
<div class="sourceCode" id="cb42"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">barred_owls_sf</span> <span class="op">&lt;-</span> <span class="va">barred_owls_sf</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_transform.html">st_transform</a></span><span class="op">(</span><span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_crs.html">st_crs</a></span><span class="op">(</span><span class="va">parks</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_join.html">st_join</a></span><span class="op">(</span><span class="va">parks</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span>outside_park <span class="op">=</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/if_else.html">if_else</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">OC_NAME</span><span class="op">)</span>, <span class="st">"Outside Park"</span>, <span class="st">"Inside Park"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p>And now we can see that there are quite a few, if not more, observations outside of parks than in.</p>
<div class="sourceCode" id="cb43"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">ggplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_sf</span><span class="op">(</span>data <span class="op">=</span> <span class="va">ab</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_sf</span><span class="op">(</span>data <span class="op">=</span> <span class="va">parks</span>, colour <span class="op">=</span> <span class="st">"darkgreen"</span>, fill <span class="op">=</span> <span class="st">"forestgreen"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_sf</span><span class="op">(</span>data <span class="op">=</span> <span class="va">barred_owls_sf</span>, size <span class="op">=</span> <span class="fl">1</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">facet_wrap</span><span class="op">(</span><span class="op">~</span><span class="va">outside_park</span><span class="op">)</span></code></pre></div>
<p><img src="mapping-observations_files/figure-html/unnamed-chunk-18-1.png" width="700"></p>
<p>We might also be interested in observations over time.</p>
<p>First we’ll bin our yearly observations</p>
<div class="sourceCode" id="cb44"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">barred_owls_sf</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://dplyr.tidyverse.org/reference/mutate.html">mutate</a></span><span class="op">(</span><span class="va">barred_owls_sf</span>, 
                         years <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/cut.html">cut</a></span><span class="op">(</span><span class="va">survey_year</span>, 
                                     breaks <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">1960</span>, <span class="fl">2010</span>, <span class="fl">10</span><span class="op">)</span>, 
                                     labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/seq.html">seq</a></span><span class="op">(</span><span class="fl">1960</span>, <span class="fl">2000</span>, <span class="fl">10</span><span class="op">)</span>, right <span class="op">=</span> <span class="cn">FALSE</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p>We’ll also want to see how many sample years there are per decade.</p>
<div class="sourceCode" id="cb45"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">years</span> <span class="op">&lt;-</span> <span class="va">barred_owls_sf</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">years</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>n <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/length.html">length</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/unique.html">unique</a></span><span class="op">(</span><span class="va">survey_year</span><span class="op">)</span><span class="op">)</span>, .groups <span class="op">=</span> <span class="st">"drop"</span><span class="op">)</span></code></pre></div>
<p>Now we can see how Barred Owl observations change over the years</p>
<div class="sourceCode" id="cb46"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu">ggplot</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">theme_bw</span><span class="op">(</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_sf</span><span class="op">(</span>data <span class="op">=</span> <span class="va">ab</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_sf</span><span class="op">(</span>data <span class="op">=</span> <span class="va">parks</span>, colour <span class="op">=</span> <span class="st">"darkgreen"</span>, fill <span class="op">=</span> <span class="st">"forestgreen"</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_sf</span><span class="op">(</span>data <span class="op">=</span> <span class="va">barred_owls_sf</span>, size <span class="op">=</span> <span class="fl">1.5</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_sf_text</span><span class="op">(</span>data <span class="op">=</span> <span class="va">years</span>, x <span class="op">=</span> <span class="fl">4427134</span>, y <span class="op">=</span> <span class="fl">2965275</span>, hjust <span class="op">=</span> <span class="fl">0</span>, vjust <span class="op">=</span> <span class="fl">1</span>, 
               <span class="fu">aes</span><span class="op">(</span>label <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"n = "</span>, <span class="va">n</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">facet_wrap</span><span class="op">(</span><span class="op">~</span><span class="va">years</span><span class="op">)</span></code></pre></div>
<p><img src="mapping-observations_files/figure-html/unnamed-chunk-21-1.png" width="700"></p>
</div>
<div id="presenceabsence" class="section level2">
<h2 class="hasAnchor">
<a href="#presenceabsence" class="anchor"></a>Presence/Absence</h2>
<p>We can also use some of the <code>naturecounts</code> helper functions to create presence/absence maps.</p>
<p>Here we download data from the <code>RCBIOTABASE</code> collection, make sure to keep only observations where all species and the location were reported, create a new <code>presence</code> column which is either TRUE, FALSE, or NA for each sampling event. Finally we use the <code><a href="../../reference/format_zero_fill.html">format_zero_fill()</a></code> function to fill in sampling events where cardinals (<code>species_id</code> 19360) were not detected (presence would then be 0).</p>
<div class="sourceCode" id="cb47"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">cardinals</span> <span class="op">&lt;-</span> <span class="fu"><a href="../../reference/nc_data_dl.html">nc_data_dl</a></span><span class="op">(</span>collection <span class="op">=</span> <span class="st">"RCBIOTABASE"</span>, username <span class="op">=</span> <span class="st">"testuser"</span>, 
                        info <span class="op">=</span> <span class="st">"nc_tutorial"</span><span class="op">)</span></code></pre></div>
<pre><code>## Using filters: collections (RCBIOTABASE); fields_set (BMDE2.00-min)</code></pre>
<pre><code>## Collecting available records...</code></pre>
<pre><code>##    collection nrecords
## 1 RCBIOTABASE    12614
## Total records: 12,614</code></pre>
<pre><code>## 
## Downloading records for each collection:</code></pre>
<pre><code>##   RCBIOTABASE</code></pre>
<pre><code>##     Records 1 to 5000 / 12614</code></pre>
<pre><code>##     Records 5001 to 10000 / 12614</code></pre>
<pre><code>##     Records 10001 to 12614 / 12614</code></pre>
<div class="sourceCode" id="cb56"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">cardinals_zf</span> <span class="op">&lt;-</span> <span class="va">cardinals</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/filter.html">filter</a></span><span class="op">(</span><span class="va">AllSpeciesReported</span> <span class="op">==</span> <span class="st">"Yes"</span>, <span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">latitude</span><span class="op">)</span>, <span class="op">!</span><span class="fu"><a href="https://rdrr.io/r/base/NA.html">is.na</a></span><span class="op">(</span><span class="va">longitude</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/group_by.html">group_by</a></span><span class="op">(</span><span class="va">species_id</span>, <span class="va">AllSpeciesReported</span>, <span class="va">SamplingEventIdentifier</span>, <span class="va">latitude</span>, <span class="va">longitude</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://dplyr.tidyverse.org/reference/summarise.html">summarize</a></span><span class="op">(</span>presence <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/sum.html">sum</a></span><span class="op">(</span><span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="va">ObservationCount</span><span class="op">)</span><span class="op">)</span> <span class="op">&gt;</span> <span class="fl">0</span>, .groups <span class="op">=</span> <span class="st">"drop"</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="../../reference/format_zero_fill.html">format_zero_fill</a></span><span class="op">(</span>species <span class="op">=</span> <span class="fl">19360</span>,
                   by <span class="op">=</span> <span class="st">"SamplingEventIdentifier"</span>,
                   extra_event <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"latitude"</span>, <span class="st">"longitude"</span><span class="op">)</span>,
                   fill <span class="op">=</span> <span class="st">"presence"</span><span class="op">)</span></code></pre></div>
<pre><code>##  - Converted 'fill' column (presence) from logical to numeric</code></pre>
<div class="sourceCode" id="cb58"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/r/utils/head.html">head</a></span><span class="op">(</span><span class="va">cardinals_zf</span><span class="op">)</span></code></pre></div>
<pre><code>##   SamplingEventIdentifier species_id presence latitude longitude
## 1     RCBIOTABASE-10000-1      19360        0 45.58604 -77.48721
## 2     RCBIOTABASE-10001-1      19360        0 45.51110 -77.50533
## 3     RCBIOTABASE-10002-1      19360        0 45.50803 -77.50786
## 4     RCBIOTABASE-10003-1      19360        0 45.51110 -77.50533
## 5     RCBIOTABASE-10004-1      19360        0 45.51110 -77.50533
## 6     RCBIOTABASE-10005-1      19360        0 45.51110 -77.50533</code></pre>
<p>Now that we have our presence/absence data for cardinals, we can create a map.</p>
<div class="sourceCode" id="cb60"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="va">map</span> <span class="op">&lt;-</span> <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_as_sf.html">st_as_sf</a></span><span class="op">(</span><span class="va">cardinals_zf</span>, coords <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"longitude"</span>, <span class="st">"latitude"</span><span class="op">)</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://r-spatial.github.io/sf/reference/st_bbox.html">st_bbox</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/r/base/numeric.html">as.numeric</a></span><span class="op">(</span><span class="op">)</span> <span class="op">%&gt;%</span>
  <span class="fu"><a href="https://rdrr.io/pkg/ggmap/man/get_stamenmap.html">get_stamenmap</a></span><span class="op">(</span>bbox <span class="op">=</span> <span class="va">.</span>, zoom <span class="op">=</span> <span class="fl">8</span><span class="op">)</span></code></pre></div>
<pre><code>## Source : http://tile.stamen.com/terrain/8/72/90.png</code></pre>
<pre><code>## Source : http://tile.stamen.com/terrain/8/73/90.png</code></pre>
<pre><code>## Source : http://tile.stamen.com/terrain/8/72/91.png</code></pre>
<pre><code>## Source : http://tile.stamen.com/terrain/8/73/91.png</code></pre>
<div class="sourceCode" id="cb65"><pre class="downlit sourceCode r">
<code class="sourceCode R"><span class="fu"><a href="https://rdrr.io/pkg/ggmap/man/ggmap.html">ggmap</a></span><span class="op">(</span><span class="va">map</span>, base_layer <span class="op">=</span> <span class="fu">ggplot</span><span class="op">(</span>data <span class="op">=</span> <span class="va">cardinals_zf</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">geom_count</span><span class="op">(</span>alpha <span class="op">=</span> <span class="fl">0.75</span>,
             <span class="fu">aes</span><span class="op">(</span>x <span class="op">=</span> <span class="va">longitude</span>, y <span class="op">=</span> <span class="va">latitude</span>, colour <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/factor.html">factor</a></span><span class="op">(</span><span class="va">presence</span><span class="op">)</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">scale_colour_manual</span><span class="op">(</span>name <span class="op">=</span> <span class="st">"Presence/Absence"</span>, values <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"yellow"</span>, <span class="st">"purple"</span><span class="op">)</span>, 
                      labels <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="st">"1"</span> <span class="op">=</span> <span class="st">"Present"</span>, <span class="st">"0"</span> <span class="op">=</span> <span class="st">"Absent"</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">scale_size_continuous</span><span class="op">(</span>name <span class="op">=</span> <span class="st">"Number of Sampling Events"</span>, range <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/c.html">c</a></span><span class="op">(</span><span class="fl">1</span>, <span class="fl">20</span><span class="op">)</span><span class="op">)</span> <span class="op">+</span>
  <span class="fu">labs</span><span class="op">(</span>title <span class="op">=</span> <span class="fu"><a href="https://rdrr.io/r/base/paste.html">paste0</a></span><span class="op">(</span><span class="st">"Presence/Absence of Cardinals in the RCBIOTABASE collection"</span><span class="op">)</span><span class="op">)</span></code></pre></div>
<p><img src="mapping-observations_files/figure-html/unnamed-chunk-23-1.png" width="700"></p>
</div>
<div id="see-also" class="section level2">
<h2 class="hasAnchor">
<a href="#see-also" class="anchor"></a>See Also</h2>
<ul>
<li><a href="region-spatial.html">Using spatial data to filter observations</a></li>
<li><a href="../region-areas.html">Exploring regional filters</a></li>
</ul>
</div>
  </div>

  <div class="col-md-3 hidden-xs hidden-sm" id="pkgdown-sidebar">

        <nav id="toc" data-toggle="toc"><h2 data-toc-skip>Contents</h2>
    </nav>
</div>

</div>



      <footer><div class="copyright">
  <p>Developed by Steffi LaZerte, Denis LePage.</p>
</div>

<div class="pkgdown">
  <p>Site built with <a href="https://pkgdown.r-lib.org/">pkgdown</a> 1.6.1.</p>
</div>

      </footer>
</div>

  


  </body>
</html>
